/* Generated By:JavaCC: Do not edit this line. TinySyntaxAnalyzerConstants.java */
package synt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinySyntaxAnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 1;
  /** RegularExpression Id. */
  int pos_digit = 2;
  /** RegularExpression Id. */
  int digit = 3;
  /** RegularExpression Id. */
  int integer = 4;
  /** RegularExpression Id. */
  int parte_dec = 5;
  /** RegularExpression Id. */
  int parte_exp = 6;
  /** RegularExpression Id. */
  int pos_zero = 7;
  /** RegularExpression Id. */
  int intt = 10;
  /** RegularExpression Id. */
  int real = 11;
  /** RegularExpression Id. */
  int bool = 12;
  /** RegularExpression Id. */
  int ttrue = 13;
  /** RegularExpression Id. */
  int ffalse = 14;
  /** RegularExpression Id. */
  int and = 15;
  /** RegularExpression Id. */
  int or = 16;
  /** RegularExpression Id. */
  int not = 17;
  /** RegularExpression Id. */
  int identificador = 18;
  /** RegularExpression Id. */
  int numInt = 19;
  /** RegularExpression Id. */
  int numReal = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letter>",
    "<pos_digit>",
    "<digit>",
    "<integer>",
    "<parte_dec>",
    "<parte_exp>",
    "<pos_zero>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<identificador>",
    "<numInt>",
    "<numReal>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
  };

}
