
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 18 11:02:39 CET 2020
//----------------------------------------------------

package synt;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int AND = 8;
  public static final int SEMICOLON = 22;
  public static final int PLUS = 17;
  public static final int OR = 9;
  public static final int INT = 2;
  public static final int EQUAL = 14;
  public static final int NOT = 21;
  public static final int END = 23;
  public static final int CLPAR = 27;
  public static final int OPPAR = 26;
  public static final int TRUE = 6;
  public static final int NUMINT = 25;
  public static final int DISEQUIV = 16;
  public static final int MULT = 19;
  public static final int MAYOR = 10;
  public static final int MINOREQUAL = 13;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int NUMREAL = 24;
  public static final int EQUIV = 15;
  public static final int MINOR = 11;
  public static final int MINUS = 18;
  public static final int FALSE = 7;
  public static final int MAYOREQUAL = 12;
  public static final int error = 1;
  public static final int BOOL = 4;
  public static final int REAL = 3;
  public static final int VAR = 5;
}

