
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed May 20 10:01:44 CEST 2020
//----------------------------------------------------

package astconstructor;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int CORCE = 2;
  public static final int RESTO = 3;
  public static final int MULT = 4;
  public static final int INT = 5;
  public static final int ARRAY = 6;
  public static final int DELETE = 8;
  public static final int WRITE = 7;
  public static final int LLACE = 9;
  public static final int NOT = 10;
  public static final int MENORIGUAL = 11;
  public static final int AND = 12;
  public static final int IGUAL = 13;
  public static final int RECORD = 14;
  public static final int TYPE = 15;
  public static final int OR = 16;
  public static final int NONEQUIV = 17;
  public static final int BOOL = 18;
  public static final int CALL = 19;
  public static final int PARAB = 20;
  public static final int DIV = 21;
  public static final int IF = 22;
  public static final int ENDWHILE = 23;
  public static final int MAYORIGUAL = 25;
  public static final int OF = 24;
  public static final int PYCOMA = 26;
  public static final int EOF = 0;
  public static final int TRUE = 27;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int CADENA = 30;
  public static final int MENOS = 31;
  public static final int NULL = 32;
  public static final int MENOR = 33;
  public static final int NUMREAL = 34;
  public static final int MAYOR = 36;
  public static final int REAL = 35;
  public static final int CORAB = 38;
  public static final int FLECHA = 37;
  public static final int PARCE = 40;
  public static final int ENDIF = 39;
  public static final int ELSE = 41;
  public static final int PUNTO = 42;
  public static final int READ = 44;
  public static final int NL = 43;
  public static final int IDEN = 45;
  public static final int WHILE = 46;
  public static final int EQUIV = 47;
  public static final int THEN = 48;
  public static final int NUMINT = 49;
  public static final int END = 50;
  public static final int STRING = 52;
  public static final int PROC = 51;
  public static final int FALSE = 54;
  public static final int POINTER = 53;
  public static final int LLAAB = 57;
  public static final int UMPERSAND = 56;
  public static final int VAR = 55;
  public static final int DO = 58;
  public static final int MAS = 59;
}

