package jaime;

/*
    SEMICOLON: ;
    OPPAR: (
    CLPAR: )
    IDEN: 
*/
public enum LexicalClass{
    EOF, SEPARATOR, NUM, NUMBER, BOOL, VAR, SEMICOLON, TRUE, 
    FALSE, EQUAL, PLUS, MINUS, POR, DIV, OR, AND, NOT, MAJOR, 
    MINOR, MEQUAL, LEQUAL, EQUIV, NONEQUIV, NEG, OPPAR, CLPAR
}