
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed May 13 13:42:27 CEST 2020
//----------------------------------------------------

package lex;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int CORCE = 19;
  public static final int RESTO = 7;
  public static final int MULT = 5;
  public static final int INT = 26;
  public static final int ARRAY = 47;
  public static final int WRITE = 53;
  public static final int DELETE = 51;
  public static final int LLACE = 21;
  public static final int NOT = 33;
  public static final int MENORIGUAL = 11;
  public static final int AND = 31;
  public static final int IGUAL = 17;
  public static final int RECORD = 46;
  public static final int TYPE = 56;
  public static final int OR = 32;
  public static final int NONEQUIV = 13;
  public static final int BOOL = 28;
  public static final int CALL = 45;
  public static final int PARAB = 14;
  public static final int DIV = 6;
  public static final int IF = 38;
  public static final int ENDWHILE = 44;
  public static final int OF = 48;
  public static final int MAYORIGUAL = 10;
  public static final int PYCOMA = 16;
  public static final int EOF = 0;
  public static final int TRUE = 35;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CADENA = 59;
  public static final int MENOS = 4;
  public static final int NULL = 34;
  public static final int MENOR = 9;
  public static final int NUMREAL = 58;
  public static final int REAL = 27;
  public static final int MAYOR = 8;
  public static final int FLECHA = 23;
  public static final int CORAB = 18;
  public static final int ENDIF = 41;
  public static final int PARCE = 15;
  public static final int ELSE = 40;
  public static final int PUNTO = 22;
  public static final int NL = 54;
  public static final int READ = 52;
  public static final int IDEN = 29;
  public static final int WHILE = 42;
  public static final int EQUIV = 12;
  public static final int THEN = 39;
  public static final int NUMINT = 57;
  public static final int END = 2;
  public static final int PROC = 37;
  public static final int STRING = 30;
  public static final int POINTER = 49;
  public static final int FALSE = 36;
  public static final int VAR = 55;
  public static final int UMPERSAND = 25;
  public static final int LLAAB = 20;
  public static final int DO = 43;
  public static final int MAS = 3;
}

