
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 15 14:48:42 CEST 2020
//----------------------------------------------------

package astconstructor;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int AND = 14;
  public static final int SEMICOLON = 26;
  public static final int NEG = 23;
  public static final int PLUS = 10;
  public static final int OR = 15;
  public static final int INT = 2;
  public static final int EQUAL = 9;
  public static final int NOT = 16;
  public static final int END = 6;
  public static final int CLPAR = 25;
  public static final int OPPAR = 24;
  public static final int IDEN = 5;
  public static final int TRUE = 7;
  public static final int NUMINT = 28;
  public static final int MINOREQUAL = 20;
  public static final int MAYOR = 17;
  public static final int EOF = 0;
  public static final int MULT = 12;
  public static final int DIV = 13;
  public static final int NUMREAL = 27;
  public static final int EQUIV = 21;
  public static final int MINOR = 18;
  public static final int MAYOREQUAL = 19;
  public static final int FALSE = 8;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int BOOL = 4;
  public static final int REAL = 3;
  public static final int NONEQUIV = 22;
}

