package ast;

public enum TipoE {
	SUMA, RESTA, MULT, DIV, RESTO, AND, OR, NOT,
	MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, EQUIV,
	NONEQUIV, NEG, IDEN, NUMREAL, NUMINT, TRUE,
	FALSE, CADENA, IDENT, NULL, INDEX, ACCESS,
	INDIRECT
}
